#!/usr/bin/env bash

set -e
set -o pipefail

repoarg=""
partialarg=""
declare -a args
for arg; do
	if [[ -n "${partialarg}" ]]; then
		repoarg="${partialarg} ${arg}"
		partialarg=""
		continue
	fi
	case "${arg}" in
		-R)
			partialarg="${arg}"
			;;
		*)
			args+=("${arg}")
			;;
	esac
done

pr="${args[-1]}"
unset args[-1]

declare -a pr_info
readarray -t pr_info < <(gh pr view ${repoarg} --json commits,headRefName -q '.commits[-1].oid,.headRefName' "${pr}")
gh run download ${repoarg} "${args[@]}" $(gh run ${repoarg} list -b "${pr_info[1]}" --json databaseId,headSha -q "map(select(.headSha==\"${pr_info[0]}\"))[0].databaseId")
